"""Documentation size monitor.

Ports .ss/scripts/check-docs-size.sh + generate-docs-size-report.py into
one self-contained check. Reads thresholds from .slopstopper.yml's
hygiene.docs_size.* keys (defaulting to today's hardcoded values), writes
.ss/reports/docs/docs-size-report.md, and prints a coloured summary to
stdout. Exits 0 always — alerts are reported, not enforced.

Goal during the CLI pivot: byte-equivalent report output to the bash
script (modulo the timestamp line), so adopters see no diff on migration.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from slopstopper import config

DOCS_DIR = Path("docs")
ARCHIVE_PREFIX = Path("docs/archive")
REPORT_DIR = Path(".ss/reports/docs")
REPORT_FILE = REPORT_DIR / "docs-size-report.md"

DEFAULT_MAX_TOTAL_SIZE_KB = 150
DEFAULT_MAX_FILE_SIZE_KB = 20
DEFAULT_MAX_FILES = 25

RED = "\033[0;31m"
GREEN = "\033[0;32m"
BLUE = "\033[0;34m"
NC = "\033[0m"


def _iter_doc_files() -> list[Path]:
    if not DOCS_DIR.exists():
        return []
    return [
        p
        for p in sorted(DOCS_DIR.rglob("*.md"))
        if ARCHIVE_PREFIX not in p.parents
    ]


def _format_largest(files_with_size: list[tuple[Path, int]]) -> str:
    top5 = sorted(files_with_size, key=lambda fs: fs[1], reverse=True)[:5]
    return "\n".join(f"{p} ({size // 1024} KB)" for p, size in top5)


def _build_report_md(
    *,
    file_count: int,
    total_size_kb: int,
    estimated_tokens: int,
    avg_size_kb: int,
    largest_files: str,
    has_alerts: bool,
    alerts: str,
    max_total_size_kb: int,
    max_file_size_kb: int,
    max_files: int,
) -> str:
    status_line = (
        "❌ Documentation size exceeds thresholds!"
        if has_alerts
        else "✅ Documentation size within acceptable limits"
    )
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    report = (
        f"# 📚 Documentation Size Report\n"
        f"\n"
        f"**Generated:** {generated}\n"
        f"\n"
        f"## Summary\n"
        f"\n"
        f"- **Total Files:** {file_count}\n"
        f"- **Total Size:** {total_size_kb} KB\n"
        f"- **Estimated Tokens:** ~{estimated_tokens}\n"
        f"- **Average File Size:** {avg_size_kb} KB\n"
        f"\n"
        f"## Largest Files\n"
        f"\n"
        f"```\n"
        f"{largest_files}\n"
        f"```\n"
        f"\n"
        f"## Status\n"
        f"\n"
        f"{status_line}\n"
        f"\n"
    )
    if has_alerts and alerts:
        report += f"### Alerts\n\n{alerts}\n\n"
    report += (
        f"## Thresholds\n"
        f"\n"
        f"- **Max Total Size:** {max_total_size_kb} KB\n"
        f"- **Max File Size:** {max_file_size_kb} KB\n"
        f"- **Max File Count:** {max_files}\n"
        f"\n"
        f"## Recommendations\n"
        f"\n"
        f"If thresholds are exceeded:\n"
        f"- Consider consolidating related documentation\n"
        f"- Move historical/completed content to archive\n"
        f"- Split large files into focused topics\n"
        f"- Remove redundant information\n"
        f"\n"
        f"---\n"
        f"\n"
        f"*This report was generated by the Documentation Size Monitor.*\n"
    )
    return report


def _config_int(path: str, default: int) -> int:
    raw = config.get(path, default)
    try:
        return int(raw)
    except (TypeError, ValueError):
        return default


def run() -> int:
    max_total_size_kb = _config_int("hygiene.docs_size.max_total_size_kb", DEFAULT_MAX_TOTAL_SIZE_KB)
    max_file_size_kb = _config_int("hygiene.docs_size.max_file_size_kb", DEFAULT_MAX_FILE_SIZE_KB)
    max_files = _config_int("hygiene.docs_size.max_files", DEFAULT_MAX_FILES)

    print()
    print("📚 Documentation Size Monitor")
    print("━" * 56)
    print()

    files = _iter_doc_files()
    files_with_size = [(p, p.stat().st_size) for p in files]

    file_count = len(files_with_size)
    total_size = sum(size for _, size in files_with_size)
    total_size_kb = total_size // 1024
    estimated_tokens = total_size // 4
    avg_size_kb = (total_size // file_count // 1024) if file_count else 0

    largest_files = _format_largest(files_with_size)

    print("📊 Documentation Statistics:")
    print("━" * 56)
    print(f"  Total Files:        {BLUE}{file_count}{NC}")
    print(f"  Total Size:         {BLUE}{total_size_kb} KB{NC}")
    print(f"  Estimated Tokens:   {BLUE}~{estimated_tokens}{NC}")
    print(f"  Average File Size:  {BLUE}{avg_size_kb} KB{NC}")
    print()

    print("📈 Largest Files:")
    print("━" * 56)
    print(largest_files)
    print()

    alerts_parts: list[str] = []
    if total_size_kb > max_total_size_kb:
        alerts_parts.append(
            f"⚠️  Total documentation size ({total_size_kb} KB) exceeds threshold ({max_total_size_kb} KB)"
        )
    if file_count > max_files:
        alerts_parts.append(
            f"⚠️  Number of documentation files ({file_count}) exceeds threshold ({max_files})"
        )
    oversized = [p for p, size in files_with_size if size > max_file_size_kb * 1024]
    if oversized:
        oversized_lines = "\n".join(f"     - {p.name}" for p in oversized)
        alerts_parts.append(f"⚠️  Files exceeding {max_file_size_kb} KB:\n{oversized_lines}")

    has_alerts = bool(alerts_parts)
    alerts = "\n".join(alerts_parts) + ("\n" if alerts_parts else "")

    print("📋 Threshold Limits:")
    print("━" * 56)
    print(f"  Max Total Size:     {BLUE}{max_total_size_kb} KB{NC}")
    print(f"  Max File Size:      {BLUE}{max_file_size_kb} KB{NC}")
    print(f"  Max File Count:     {BLUE}{max_files}{NC}")
    print()

    if has_alerts:
        print(f"{RED}❌ Status: THRESHOLDS EXCEEDED{NC}")
        print()
        print("⚠️  Alerts:")
        print("━" * 56)
        print(alerts)
    else:
        print(f"{GREEN}✅ Status: Within acceptable limits{NC}")
    print()

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_md = _build_report_md(
        file_count=file_count,
        total_size_kb=total_size_kb,
        estimated_tokens=estimated_tokens,
        avg_size_kb=avg_size_kb,
        largest_files=largest_files,
        has_alerts=has_alerts,
        alerts=alerts,
        max_total_size_kb=max_total_size_kb,
        max_file_size_kb=max_file_size_kb,
        max_files=max_files,
    )
    REPORT_FILE.write_text(report_md)

    print(f"📁 Reports saved to: {REPORT_DIR}/")
    print(f"   • {REPORT_FILE.name} (human-readable)")
    print()

    return 0
