"""Entry-file size budget check.

Ports .ss/scripts/check-entry-file-size.py. Enforces the "thin pointer"
principle declared in docs/index.md: agent entry files (README.md,
AGENTS.md, CLAUDE.md) stay under a word budget so they don't crowd
the context window of every agent conversation.

Reads the budget from .slopstopper.yml's hygiene.entry_files.max_words
key (defaulting to 1500 — ≈ 2k tokens for English prose). Writes a
markdown report and a JSON report under .ss/reports/entry-files/.

Exit codes mirror the bash version:
  0 — all entry files within budget
  1 — at least one file exceeds the budget
  2 — required input files missing
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from slopstopper import config

ENTRY_FILES = ("README.md", "AGENTS.md", "CLAUDE.md")
DEFAULT_MAX_WORDS = 1500
REPORT_DIR = Path(".ss/reports/entry-files")
REPORT_MD = REPORT_DIR / "entry-file-size-report.md"
REPORT_JSON = REPORT_DIR / "entry-file-size-report.json"

_WORD_RE = re.compile(r"\S+")


def _config_int(path: str, default: int) -> int:
    raw = config.get(path, default)
    try:
        return int(raw)
    except (TypeError, ValueError):
        return default


def _load_max_words() -> int:
    return _config_int("hygiene.entry_files.max_words", DEFAULT_MAX_WORDS)


def _count_words(path: Path) -> int:
    return len(_WORD_RE.findall(path.read_text()))


def _measure(name: str, max_words: int) -> dict | None:
    path = Path(name)
    if not path.exists():
        return None
    words = _count_words(path)
    return {
        "file": name,
        "words": words,
        "budget": max_words,
        "over_budget": words > max_words,
        "headroom": max_words - words,
    }


def _measure_all(max_words: int) -> tuple[list[dict], list[str]]:
    measurements: list[dict] = []
    missing: list[str] = []
    for name in ENTRY_FILES:
        m = _measure(name, max_words)
        if m is None:
            missing.append(name)
        else:
            measurements.append(m)
    return measurements, missing


def _generated_at() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _status_line(clean: bool, max_words: int) -> str:
    if clean:
        return "✅ All entry files within budget."
    return f"❌ One or more entry files exceed the {max_words:,}-word budget."


def _md_row(m: dict) -> str:
    status = "❌ over" if m["over_budget"] else "✅ ok"
    return (
        f"| `{m['file']}` | {m['words']} | {m['budget']} | "
        f"{status} | {m['headroom']:+d} |"
    )


def _build_md_report(measurements: list[dict], generated_at: str, status_line: str) -> str:
    rows = "\n".join(_md_row(m) for m in measurements)
    return f"""# 📏 Entry-File Size Report

**Generated:** {generated_at}

The repo's agent entry files (`README.md`, `AGENTS.md`, `CLAUDE.md`)
are loaded into every agent conversation. `docs/index.md` declares
that they should stay under ~2k tokens each so they don't crowd the
context window. This check enforces that with a 1,500-word cap
(≈ 2k tokens for English prose).

## Measurements

| File | Words | Budget | Status | Headroom |
| ---- | ----- | ------ | ------ | -------- |
{rows}

## Status

{status_line}

## How to fix violations

Move the over-budget file's bulk into the category README under
`docs/` that owns the topic, leaving a one-line pointer in the
entry file. See [the map pattern](../../docs/index.md#the-map-pattern).

---

*Generated by `task ss:hygiene:entry-files`.*
"""


def _build_json_report(
    measurements: list[dict], generated_at: str, max_words: int, clean: bool
) -> str:
    payload = {
        "generated_at": generated_at,
        "budget_words": max_words,
        "measurements": measurements,
        "clean": clean,
        "violation_count": sum(1 for m in measurements if m["over_budget"]),
    }
    return json.dumps(payload, indent=2)


def _print_summary(measurements: list[dict], status_line: str) -> None:
    print("📏 Entry-file size budget check")
    print("━" * 56)
    for m in measurements:
        marker = "❌" if m["over_budget"] else "✅"
        print(
            f"  {marker} {m['file']:<14} {m['words']:>5} words  "
            f"(budget {m['budget']}, headroom {m['headroom']:+d})"
        )
    print()
    print(status_line)
    print(f"📁 Reports saved to: {REPORT_DIR}/")


def run(_args: list[str] | None = None) -> int:
    max_words = _load_max_words()
    measurements, missing = _measure_all(max_words)

    if missing:
        print(f"❌ Required entry files not found: {', '.join(missing)}")
        return 2

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    clean = not any(m["over_budget"] for m in measurements)
    generated_at = _generated_at()
    status_line = _status_line(clean, max_words)

    REPORT_JSON.write_text(_build_json_report(measurements, generated_at, max_words, clean))
    REPORT_MD.write_text(_build_md_report(measurements, generated_at, status_line))

    _print_summary(measurements, status_line)
    return 0 if clean else 1
