"""Secrets detection (Gitleaks wrapper).

Ports the bash security:secrets flow into one self-contained check:

  task secrets:check-tool   (installs gitleaks if missing)
  + gitleaks detect --source=. --report-format=json --report-path=...
  + python3 .ss/scripts/generate-secrets-md.py

Subprocess-invokes `gitleaks` — the same licensing-boundary pattern as
complexity (lizard). Adopters install gitleaks themselves (MIT). The
slopstopper-cli wheel ships zero gitleaks code.

Exit codes:
  0 — analysis completed (gating happens at the workflow level)
  1 — gitleaks is not installed
"""

from __future__ import annotations

import json
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPORT_DIR = Path(".ss/reports/secrets")
REPORT_JSON = REPORT_DIR / "secrets-report.json"
REPORT_MD = REPORT_DIR / "secrets-report.md"

_INSTALL_HELP = (
    "❌ gitleaks is not installed.\n"
    "Install with:\n"
    "  brew install gitleaks                   # macOS\n"
    "  sudo apt-get install gitleaks           # Debian/Ubuntu (recent versions)\n"
    "Or pre-built binary from https://github.com/gitleaks/gitleaks/releases"
)


def _gitleaks_available() -> bool:
    return shutil.which("gitleaks") is not None


def _run_gitleaks() -> None:
    """Invoke `gitleaks detect --source=. ...`.

    Exit code 1 from gitleaks means findings — that's expected and not an
    error of the check. We rely on report file content, not the exit code.
    """
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "gitleaks", "detect",
            "--source=.",
            "--report-format=json",
            f"--report-path={REPORT_JSON}",
        ],
        check=False,
    )


def _read_findings() -> list[dict]:
    if not REPORT_JSON.exists():
        return []
    content = REPORT_JSON.read_text().strip()
    if not content or content == "null":
        return []
    try:
        data = json.loads(content)
    except json.JSONDecodeError:
        return []
    return data if isinstance(data, list) else []


def _format_finding_row(finding: dict) -> str:
    rule_id = finding.get("RuleID", finding.get("ruleID", "unknown"))
    description = finding.get("Description", finding.get("description", ""))
    file_path = finding.get("File", finding.get("file", "unknown"))
    line = finding.get("StartLine", finding.get("startLine", "?"))
    commit = finding.get("Commit", finding.get("commit", ""))
    short_commit = commit[:8] if commit else "working tree"
    location = f"`{file_path}:{line}`"
    desc_truncated = (description[:57] + "...") if len(description) > 60 else description
    return f"| {rule_id} | {location} | {short_commit} | {desc_truncated} |"


def _generated_at() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")


def _build_md_report(findings: list[dict]) -> str:
    total = len(findings)
    md = "# Secrets Detection Report\n\n"
    md += f"**Generated**: {_generated_at()}\n\n"
    md += "## Summary\n\n"
    if total == 0:
        md += "## ✅ Secrets Status\n\nNo secrets detected.\n\n"
    else:
        md += f"> ⚠️ **{total} secret(s) detected** — revoke and remove immediately.\n\n"
        md += "| Rule | Location | Commit | Description |\n"
        md += "|------|----------|--------|-------------|\n"
        for finding in findings:
            md += _format_finding_row(finding) + "\n"
        md += "\n"
    md += "## Guidelines\n\n"
    md += "- **If secrets are found**: Revoke the credential immediately, then remove it from the codebase and git history\n"
    md += "- Use environment variables or a secrets manager instead of hardcoding credentials\n"
    md += "- Consider adding a `.gitleaks.toml` to tune rules for your project\n"
    md += "- Run `task secrets` locally before pushing to catch issues early\n\n"
    md += "## More Information\n\n"
    md += "- Generated by [Gitleaks](https://gitleaks.io/)\n"
    md += "- Reports location: `.ss/reports/secrets/`\n"
    md += "  - `secrets-report.md` (this file)\n"
    md += "  - `secrets-report.json` (machine-readable)\n"
    return md


def run(_args: list[str] | None = None) -> int:
    if not _gitleaks_available():
        print(_INSTALL_HELP)
        return 1

    print("🔑 Running secrets detection…")
    _run_gitleaks()
    findings = _read_findings()
    REPORT_MD.write_text(_build_md_report(findings))

    if findings:
        print(f"⚠️  Found {len(findings)} secret(s) — revoke and remove immediately")
    else:
        print("✅ No secrets detected")
    print(f"📁 Reports saved to: {REPORT_DIR}/")
    return 0
