#!/usr/bin/env python3

"""
Entry-File Size Budget Check

Enforces the "thin pointer" principle declared in docs/index.md:
agent entry files (README.md, AGENTS.md, CLAUDE.md) stay under
~2k tokens each, so they don't crowd the context window of every
agent conversation.

Threshold is expressed in words because word counts are stable
across tokenisers; the 1,500-word cap maps to roughly 2k tokens
for English prose.

Writes reports at .ss/reports/entry-files/entry-file-size-report.{md,json}.

Exit codes:
  0 — all entry files within budget
  1 — at least one file exceeds the budget
  2 — required input files missing
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ENTRY_FILES = ("README.md", "AGENTS.md", "CLAUDE.md")
MAX_WORDS = 1500
REPORT_DIR = Path(".ss/reports/entry-files")

_WORD_RE = re.compile(r"\S+")


def count_words(path: Path) -> int:
    return len(_WORD_RE.findall(path.read_text()))


def measure(name: str) -> dict | None:
    path = Path(name)
    if not path.exists():
        return None
    words = count_words(path)
    return {
        "file": name,
        "words": words,
        "budget": MAX_WORDS,
        "over_budget": words > MAX_WORDS,
        "headroom": MAX_WORDS - words,
    }


def _row(m: dict) -> str:
    status = "❌ over" if m["over_budget"] else "✅ ok"
    return (
        f"| `{m['file']}` | {m['words']} | {m['budget']} | "
        f"{status} | {m['headroom']:+d} |"
    )


def _status_line(clean: bool) -> str:
    if clean:
        return "✅ All entry files within budget."
    return "❌ One or more entry files exceed the 1,500-word budget."


def _md_report(measurements: list[dict], generated_at: str, status_line: str) -> str:
    rows = "\n".join(_row(m) for m in measurements)
    return f"""# 📏 Entry-File Size Report

**Generated:** {generated_at}

The repo's agent entry files (`README.md`, `AGENTS.md`, `CLAUDE.md`)
are loaded into every agent conversation. `docs/index.md` declares
that they should stay under ~2k tokens each so they don't crowd the
context window. This check enforces that with a 1,500-word cap
(≈ 2k tokens for English prose).

## Measurements

| File | Words | Budget | Status | Headroom |
| ---- | ----- | ------ | ------ | -------- |
{rows}

## Status

{status_line}

## How to fix violations

Move the over-budget file's bulk into the category README under
`docs/` that owns the topic, leaving a one-line pointer in the
entry file. See [the map pattern](../../docs/index.md#the-map-pattern).

---

*Generated by `task ss:hygiene:entry-files`.*
"""


def _print_summary(measurements: list[dict], status_line: str) -> None:
    print("📏 Entry-file size budget check")
    print("━" * 56)
    for m in measurements:
        marker = "❌" if m["over_budget"] else "✅"
        print(
            f"  {marker} {m['file']:<14} {m['words']:>5} words  "
            f"(budget {m['budget']}, headroom {m['headroom']:+d})"
        )
    print()
    print(status_line)
    print(f"📁 Reports saved to: {REPORT_DIR}/")


def main() -> int:
    measurements: list[dict] = []
    missing: list[str] = []
    for name in ENTRY_FILES:
        m = measure(name)
        (missing if m is None else measurements).append(name if m is None else m)

    if missing:
        print(f"❌ Required entry files not found: {', '.join(missing)}")
        return 2

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    clean = not any(m["over_budget"] for m in measurements)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    status_line = _status_line(clean)

    json_report = {
        "generated_at": generated_at,
        "budget_words": MAX_WORDS,
        "measurements": measurements,
        "clean": clean,
        "violation_count": sum(1 for m in measurements if m["over_budget"]),
    }
    (REPORT_DIR / "entry-file-size-report.json").write_text(
        json.dumps(json_report, indent=2)
    )
    (REPORT_DIR / "entry-file-size-report.md").write_text(
        _md_report(measurements, generated_at, status_line)
    )

    _print_summary(measurements, status_line)
    return 0 if clean else 1


if __name__ == "__main__":
    sys.exit(main())
