#!/usr/bin/env python3

"""
Documentation Size Report Generator

Generates a formatted markdown report from documentation size analysis.
Replicates the GitHub Actions workflow report generation locally.
"""

import argparse
import sys
from pathlib import Path
from datetime import datetime


def main():
    parser = argparse.ArgumentParser(
        description="Generate documentation size report"
    )
    parser.add_argument("--file-count", type=int, required=True)
    parser.add_argument("--total-size-kb", type=int, required=True)
    parser.add_argument("--estimated-tokens", type=int, required=True)
    parser.add_argument("--avg-size-kb", type=int, required=True)
    parser.add_argument("--largest-files", type=str, required=True)
    parser.add_argument("--has-alerts", type=str, required=True)
    parser.add_argument("--alerts", type=str, default="")

    args = parser.parse_args()

    # Parse has_alerts boolean
    has_alerts = args.has_alerts.lower() in ("true", "1", "yes")

    # Create report
    report = f"""# 📚 Documentation Size Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}

## Summary

- **Total Files:** {args.file_count}
- **Total Size:** {args.total_size_kb} KB
- **Estimated Tokens:** ~{args.estimated_tokens}
- **Average File Size:** {args.avg_size_kb} KB

## Largest Files

```
{args.largest_files}
```

## Status

{("❌ Documentation size exceeds thresholds!" if has_alerts else "✅ Documentation size within acceptable limits")}

"""

    if has_alerts and args.alerts:
        report += f"""### Alerts

{args.alerts}

"""

    report += f"""## Thresholds

- **Max Total Size:** 150 KB
- **Max File Size:** 20 KB
- **Max File Count:** 15

## Recommendations

If thresholds are exceeded:
- Consider consolidating related documentation
- Move historical/completed content to archive
- Split large files into focused topics
- Remove redundant information

---

*This report was generated by the Documentation Size Monitor.*
"""

    # Write report
    report_dir = Path(".docs-reports")
    report_dir.mkdir(exist_ok=True)

    report_file = report_dir / "docs-size-report.md"
    report_file.write_text(report)

    print(f"✅ Report generated: {report_file}")


if __name__ == "__main__":
    main()
