#!/usr/bin/env python3

"""Generate a Markdown front matter report from JSON output.

This script is used both locally (via 'task hygiene:docs-front-matter') and in CI/CD.
Reads the JSON report generated by check-docs-front-matter.py and creates a
human-readable markdown report.
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path


def read_json_report(json_path):
    """Read documentation front matter JSON report."""
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"Front matter JSON report not found at {json_path}")

    try:
        with open(json_path, "r") as f:
            data = json.load(f)
    except Exception as e:
        raise RuntimeError(f"Failed to read front matter JSON report: {e}") from e

    return data


def _format_issues_content(issues):
    """Format issues into markdown sections grouped by type."""
    content = f"Found **{len(issues)}** issue(s):\n\n"

    by_type = {}
    for issue in issues:
        by_type.setdefault(issue.get("type", "unknown"), []).append(issue)

    if "missing_front_matter" in by_type:
        content += "### Files Missing Front Matter\n\n"
        for issue in by_type["missing_front_matter"]:
            content += f"- `{issue['file']}` — {issue['message']}\n"
        content += "\n"

    if "missing_field" in by_type:
        content += "### Files with Missing Required Fields\n\n"
        for issue in by_type["missing_field"]:
            content += f"- `{issue['file']}` — {issue['message']}\n"
        content += "\n"

    if "invalid_status" in by_type:
        content += "### Files with Invalid Status Values\n\n"
        for issue in by_type["invalid_status"]:
            content += f"- `{issue['file']}` — {issue['message']}\n"
        content += "\n"

    if "invalid_date" in by_type:
        content += "### Files with Invalid Date Format\n\n"
        for issue in by_type["invalid_date"]:
            content += f"- `{issue['file']}` — {issue['message']}\n"
        content += "\n"

    return content


def generate_markdown_report(data):
    """Convert JSON report to markdown format."""
    issues = data.get("issues", [])
    is_clean = data.get("clean", True)

    report = f"""# 📄 Documentation Front Matter Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}

## Status

{("✅ All documentation files contain valid front matter" if is_clean else "❌ Front matter issues found")}

## What Is Front Matter?

YAML front matter is a block of key-value metadata placed at the very top of a markdown file, enclosed between `---` delimiters. Example:

```yaml
---
title: My Document
description: A short summary of the document.
---
```

Front matter improves discoverability, aids automated validation, and provides structured metadata for tooling and AI context.

## Required Fields

Every markdown file under `docs/` must include:

| Field | Purpose | Validation |
|-------|---------|------------|
| `title` | The human-readable title of the document | Non-empty string |
| `description` | A one-line summary of the document's purpose | Non-empty string |
| `status` | Content lifecycle state | One of: `draft`, `maintained`, `deprecated` |
| `date` | Date the document was last meaningfully updated | `YYYY-MM-DD` format |

## Issues

"""

    if issues:
        report += _format_issues_content(issues)
    else:
        report += "✅ No issues found\n\n"

    report += """## How to Fix

Add a front matter block at the very top of the file (before any other content):

```yaml
---
title: <Document Title>
description: <One-line description of the document.>
status: maintained
date: YYYY-MM-DD
---
```

`status` must be one of: `draft`, `maintained`, `deprecated`.
`date` must be in `YYYY-MM-DD` format (e.g. `2026-03-02`).

---

*Report generated by Documentation Front Matter Check*
"""

    return report


def main():
    try:
        json_path = ".ss/reports/docs/docs-front-matter-report.json"
        markdown_path = ".ss/reports/docs/docs-front-matter-report.md"

        Path(".ss/reports/docs").mkdir(parents=True, exist_ok=True)

        data = read_json_report(json_path)
        markdown = generate_markdown_report(data)

        with open(markdown_path, "w") as f:
            f.write(markdown)

        print(f"✅ Markdown report generated: {markdown_path}")

    except Exception as e:
        print(f"❌ Failed to generate markdown report: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
