#!/usr/bin/env python3

"""Generate a Markdown documentation structure report from JSON output.

This script is used both locally (via 'task hygiene:docs-structure') and in CI/CD.
Reads the JSON report generated by check-docs-structure.py and creates a
human-readable markdown report.
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path


def read_json_report(json_path):
    """Read documentation structure JSON report."""
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"Documentation structure JSON report not found at {json_path}")

    try:
        with open(json_path, "r") as f:
            data = json.load(f)
    except Exception as e:
        raise RuntimeError(f"Failed to read documentation structure JSON report: {e}") from e

    return data


def _format_violations_content(violations):
    """Format violations into markdown sections grouped by type."""
    content = f"Found **{len(violations)}** violation(s):\n\n"

    by_type = {}
    for v in violations:
        by_type.setdefault(v.get("type", "unknown"), []).append(v)

    sections = [
        ("missing_directory", "### Missing Directories\n\n", None),
        ("missing_readme", "### Missing README.md Files\n\n", None),
        ("unexpected_file", "### Unexpected Files\n\n",
         "  *Either add to `docs/index.md` or remove the file*\n"),
        ("unexpected_directory", "### Unexpected Directories\n\n",
         "  *Either add to `docs/index.md` or remove the directory*\n"),
    ]

    for vtype, header, note in sections:
        if vtype in by_type:
            content += header
            for v in by_type[vtype]:
                content += f"- {v['message']}\n"
                if note:
                    content += note
            content += "\n"

    return content


def generate_markdown_report(data):
    """Convert JSON report to markdown format."""
    violations = data.get("violations", [])
    is_valid = data.get("valid", True)

    report = f"""# 📋 Documentation Structure Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}

## Status

{("✅ Documentation structure matches governance model" if is_valid else "❌ Documentation structure violations found")}

## Governance Model

The documentation structure is governed by [`docs/index.md`](../index.md). All documentation must align with the categories and structure defined there.

**Key Principle:** The index is the **sole source of truth** for documentation structure.

## Violations

"""

    if violations:
        report += _format_violations_content(violations)
    else:
        report += "✅ No violations found\n\n"
    
    report += """## Expected Categories

The following categories are defined in `docs/index.md`:

| Category | Required | Status |
|----------|----------|--------|
| architecture/ | ✅ | Must exist with README.md |
| contributing/ | ✅ | Must exist with README.md |
| decisions/ | ✅ | Must exist with README.md |
| deployment/ | ✅ | Must exist with README.md |
| hygiene/ | ✅ | Must exist with README.md |
| reliability/ | ✅ | Must exist with README.md |
| runbooks/ | ✅ | Must exist with README.md |
| security/ | ✅ | Must exist with README.md |

## How to Fix

1. **For missing directories or README.md files:**
   - Create the directory and add a README.md with its purpose
   - See existing README.md files for the format

2. **For unexpected files:**
   - If they should be documented: Add an entry to `docs/index.md`
   - If they shouldn't exist: Delete them

3. **For unexpected directories:**
   - If they should be part of governance: Add to the table in `docs/index.md`
   - If they shouldn't exist: Delete them

## More Information

- See [`docs/index.md`](../index.md) for the governance model
- Each category README.md should document its purpose and contents

---

*Report generated by Documentation Structure Check*
"""
    
    return report


def main():
    try:
        json_path = ".docs-reports/docs-structure-report.json"
        markdown_path = ".docs-reports/docs-structure-report.md"
        
        # Ensure directory exists
        Path(".docs-reports").mkdir(exist_ok=True)
        
        # Read JSON report
        data = read_json_report(json_path)
        
        # Generate markdown
        markdown = generate_markdown_report(data)
        
        # Write markdown report
        with open(markdown_path, "w") as f:
            f.write(markdown)
        
        print(f"✅ Markdown report generated: {markdown_path}")
        
    except Exception as e:
        print(f"❌ Failed to generate markdown report: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
