#!/usr/bin/env python3
"""Generate a Markdown dependencies report from Trivy JSON output.

This script is used both locally (via 'task dependencies') and in CI/CD.
It must reliably generate reports without silently hiding errors.
"""

import json
import os
import sys
import traceback
from datetime import datetime


def read_json_report(json_path):
    """Read Trivy JSON report and return data."""
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"Dependencies JSON report not found at {json_path}")

    try:
        with open(json_path, "r") as f:
            data = json.load(f)
    except Exception as e:
        raise RuntimeError(f"Failed to read dependencies JSON report: {e}") from e

    return data


def collect_vulnerabilities(data):
    """Extract all vulnerabilities from Trivy results, grouped by severity."""
    critical = []
    high = []
    medium = []
    low = []

    for result in data.get("Results", []):
        target = result.get("Target", "unknown")
        for vuln in result.get("Vulnerabilities", []):
            entry = {
                "id": vuln.get("VulnerabilityID", "unknown"),
                "pkg": vuln.get("PkgName", "unknown"),
                "installed": vuln.get("InstalledVersion", "?"),
                "fixed": vuln.get("FixedVersion", "none"),
                "severity": vuln.get("Severity", "UNKNOWN"),
                "title": vuln.get("Title", ""),
                "target": target,
            }
            sev = entry["severity"].upper()
            if sev == "CRITICAL":
                critical.append(entry)
            elif sev == "HIGH":
                high.append(entry)
            elif sev == "MEDIUM":
                medium.append(entry)
            else:
                low.append(entry)

    return critical, high, medium, low


def format_vuln_row(v):
    """Format a single vulnerability as a markdown table row."""
    title = (v["title"][:57] + "...") if len(v["title"]) > 60 else v["title"]
    return (
        f"| {v['id']} | `{v['pkg']}` | {v['installed']} | {v['fixed']} "
        f"| {v['severity']} | {title} |"
    )


def format_vuln_section(vulns, section_title, icon):
    """Format a list of vulnerabilities as a markdown section."""
    if not vulns:
        return ""

    result = f"## {icon} {section_title}\n\n"
    result += "| CVE | Package | Installed | Fixed In | Severity | Title |\n"
    result += "|-----|---------|-----------|----------|----------|-------|\n"
    for v in vulns:
        result += format_vuln_row(v) + "\n"
    result += "\n"
    return result


def build_markdown_report(data):
    """Build the complete markdown report from Trivy JSON output."""
    critical, high, medium, low = collect_vulnerabilities(data)
    total = len(critical) + len(high) + len(medium) + len(low)
    blocking = len(critical) + len(high)

    md_content = "# Dependency Vulnerability Report\n\n"
    md_content += f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    md_content += "## Summary\n\n"

    if total == 0:
        md_content += "## ✅ Dependencies Status\n\nNo vulnerabilities detected.\n\n"
    else:
        md_content += "| Severity | Count |\n"
        md_content += "|----------|-------|\n"
        md_content += f"| 🔴 Critical | {len(critical)} |\n"
        md_content += f"| 🟠 High | {len(high)} |\n"
        md_content += f"| 🟡 Medium | {len(medium)} |\n"
        md_content += f"| 🔵 Low | {len(low)} |\n"
        md_content += f"| **Total** | **{total}** |\n\n"

        md_content += format_vuln_section(critical, "Critical Vulnerabilities", "🔴")
        md_content += format_vuln_section(high, "High Vulnerabilities", "🟠")
        md_content += format_vuln_section(medium, "Medium Vulnerabilities", "🟡")
        md_content += format_vuln_section(low, "Low Vulnerabilities", "🔵")

    md_content += "## Guidelines\n\n"
    md_content += "- **Critical/High**: Update or replace the vulnerable package before merging\n"
    md_content += "- **Medium**: Review and plan remediation\n"
    md_content += "- **Low**: Informational — update when convenient\n"
    md_content += "- Run `task dependencies` locally to reproduce\n\n"
    md_content += "## More Information\n\n"
    md_content += "- Generated by [Trivy](https://trivy.dev/)\n"
    md_content += "- Reports location: `.dependencies-reports/`\n"
    md_content += "  - `dependencies-report.md` (this file)\n"
    md_content += "  - `dependencies-report.json` (machine-readable)\n"

    return md_content, blocking


def write_report(report_path, content):
    """Write markdown report to file."""
    try:
        with open(report_path, "w") as f:
            f.write(content)
    except Exception as e:
        raise RuntimeError(f"Failed to write markdown report: {e}") from e


def main():
    """Generate markdown report from Trivy JSON output."""
    os.makedirs(".dependencies-reports", exist_ok=True)

    json_path = ".dependencies-reports/dependencies-report.json"
    report_path = ".dependencies-reports/dependencies-report.md"

    data = read_json_report(json_path)
    report_content, blocking_count = build_markdown_report(data)
    write_report(report_path, report_content)

    print("✅ Markdown report generated successfully")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"❌ Error generating markdown report: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)
