#!/usr/bin/env python3
"""Generate a Markdown DAST report from OWASP ZAP JSON output.

This script is used both locally (via 'task dast') and in CI/CD.
It must reliably generate reports without silently hiding errors.
"""

import json
import os
import sys
import traceback
from datetime import datetime


# ZAP risk code mapping
RISK_LABELS = {
    "3": "High",
    "2": "Medium",
    "1": "Low",
    "0": "Informational",
}
RISK_ICONS = {
    "3": "🔴",
    "2": "🟡",
    "1": "🔵",
    "0": "ℹ️",
}


def read_json_report(json_path):
    """Read OWASP ZAP JSON report and return data."""
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"DAST JSON report not found at {json_path}")

    try:
        with open(json_path, "r") as f:
            data = json.load(f)
    except Exception as e:
        raise RuntimeError(f"Failed to read DAST JSON report: {e}") from e

    return data


def collect_alerts(data):
    """Extract all alerts grouped by risk code."""
    alerts_by_risk = {"3": [], "2": [], "1": [], "0": []}

    for site in data.get("site", []):
        for alert in site.get("alerts", []):
            riskcode = str(alert.get("riskcode", "0"))
            entry = {
                "name": alert.get("name", alert.get("alert", "unknown")),
                "riskcode": riskcode,
                "confidence": alert.get("confidence", "?"),
                "desc": alert.get("desc", "").replace("\n", " ").strip(),
                "instances": len(alert.get("instances", [])),
                "solution": alert.get("solution", "").replace("\n", " ").strip(),
            }
            bucket = alerts_by_risk.get(riskcode, alerts_by_risk["0"])
            bucket.append(entry)

    return alerts_by_risk


def format_alert_row(alert):
    """Format a single alert as a markdown table row."""
    name = alert["name"]
    risk = RISK_LABELS.get(alert["riskcode"], "Unknown")
    instances = alert["instances"]
    desc = (alert["desc"][:77] + "...") if len(alert["desc"]) > 80 else alert["desc"]
    return f"| {name} | {risk} | {instances} | {desc} |"


def format_alert_section(alerts, section_title, icon):
    """Format a list of alerts as a markdown section."""
    if not alerts:
        return ""

    result = f"## {icon} {section_title}\n\n"
    result += "| Alert | Risk | Instances | Description |\n"
    result += "|-------|------|-----------|-------------|\n"
    for alert in alerts:
        result += format_alert_row(alert) + "\n"
    result += "\n"
    return result


def build_markdown_report(data):
    """Build the complete markdown report from ZAP JSON output."""
    alerts_by_risk = collect_alerts(data)

    high = alerts_by_risk["3"]
    medium = alerts_by_risk["2"]
    low = alerts_by_risk["1"]
    info = alerts_by_risk["0"]
    total = sum(len(v) for v in alerts_by_risk.values())
    blocking = len(high) + len(medium)

    md_content = "# DAST Analysis Report\n\n"
    md_content += f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    md_content += "## Summary\n\n"

    if total == 0:
        md_content += "## ✅ DAST Status\n\nNo alerts detected.\n\n"
    else:
        md_content += "| Risk Level | Count |\n"
        md_content += "|------------|-------|\n"
        md_content += f"| 🔴 High | {len(high)} |\n"
        md_content += f"| 🟡 Medium | {len(medium)} |\n"
        md_content += f"| 🔵 Low | {len(low)} |\n"
        md_content += f"| ℹ️ Informational | {len(info)} |\n"
        md_content += f"| **Total** | **{total}** |\n\n"

        md_content += format_alert_section(high, "High Risk Alerts", "🔴")
        md_content += format_alert_section(medium, "Medium Risk Alerts", "🟡")
        md_content += format_alert_section(low, "Low Risk Alerts", "🔵")
        md_content += format_alert_section(info, "Informational Alerts", "ℹ️")

    md_content += "## Guidelines\n\n"
    md_content += "- **High**: Must be addressed before merging\n"
    md_content += "- **Medium**: Should be reviewed and addressed\n"
    md_content += "- **Low**: Informational — review when time allows\n"
    md_content += "- Run `task dast -- <url>` locally to reproduce\n\n"
    md_content += "## More Information\n\n"
    md_content += "- Generated by [OWASP ZAP](https://www.zaproxy.org/)\n"
    md_content += "- Reports location: `.dast-reports/`\n"
    md_content += "  - `dast-report.md` (this file)\n"
    md_content += "  - `dast-report.json` (machine-readable)\n"

    return md_content, blocking


def write_report(report_path, content):
    """Write markdown report to file."""
    try:
        with open(report_path, "w") as f:
            f.write(content)
    except Exception as e:
        raise RuntimeError(f"Failed to write markdown report: {e}") from e


def main():
    """Generate markdown report from OWASP ZAP JSON output."""
    os.makedirs(".dast-reports", exist_ok=True)

    json_path = ".dast-reports/dast-report.json"
    report_path = ".dast-reports/dast-report.md"

    data = read_json_report(json_path)
    report_content, blocking_count = build_markdown_report(data)
    write_report(report_path, report_content)

    print("✅ Markdown report generated successfully")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"❌ Error generating markdown report: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)
