#!/usr/bin/env python3
"""Generate a Markdown complexity report from Lizard output.

This script is used both locally (via 'task complexity') and in CI/CD.
It must reliably generate reports without silently hiding errors.
"""

import os
import csv
from datetime import datetime
import sys
import traceback


def read_csv_report(csv_path):
    """Read CSV report and extract high complexity items."""
    high_complexity_items = []
    
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"CSV report not found at {csv_path}")
    
    try:
        with open(csv_path, "r") as f:
            reader = csv.reader(f)
            for row in reader:
                if len(row) > 1:
                    try:
                        ccn = int(row[1])
                        if ccn > 10:
                            high_complexity_items.append(row)
                    except ValueError:
                        pass
    except Exception as e:
        raise RuntimeError(f"Failed to read CSV report: {e}") from e
    
    return high_complexity_items


def read_raw_report(raw_path):
    """Extract summary from raw text report."""
    if not os.path.exists(raw_path):
        raise FileNotFoundError(f"Raw report not found at {raw_path}")
    
    try:
        with open(raw_path, "r") as f:
            raw_report = f.read()
    except Exception as e:
        raise RuntimeError(f"Failed to read raw report: {e}") from e
    
    # Find the summary section
    lines = raw_report.split('\n')
    summary_lines = []
    in_summary = False
    
    for line in lines:
        if "No thresholds exceeded" in line or "thresholds exceeded" in line:
            summary_lines.append(line)
            break
        if in_summary:
            summary_lines.append(line)
        if "Total nloc" in line:
            in_summary = True
            summary_lines.append(line)
    
    return summary_lines


def format_summary_section(summary_lines):
    """Format summary section for markdown."""
    if not summary_lines:
        return ""
    
    result = "```\n"
    result += "\n".join(summary_lines[:15])
    result += "\n```\n\n"
    return result


def format_high_complexity_section(high_complexity_items):
    """Format high complexity items section."""
    if not high_complexity_items:
        return "## ✅ Complexity Status\n\nNo high-complexity items found (all CCN ≤ 10)\n\n"
    
    result = "## ⚠️ High Complexity Items (CCN > 10)\n\n"
    result += "| NLOC | CCN | Tokens | Params | Length | Location |\n"
    result += "|------|-----|--------|--------|--------|----------|\n"
    
    for item in high_complexity_items:
        if len(item) > 5:
            nloc = item[0]
            ccn = item[1]
            tokens = item[2]
            params = item[3]
            length = item[4]
            location = item[5].strip('"') if len(item) > 5 else "unknown"
            result += f"| {nloc} | {ccn} | {tokens} | {params} | {length} | `{location}` |\n"
    
    return result


def build_markdown_report(summary_lines, high_complexity_items):
    """Build the complete markdown report."""
    md_content = "# Code Complexity Analysis Report\n\n"
    md_content += f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    md_content += "## Summary\n\n"
    
    md_content += format_summary_section(summary_lines)
    md_content += format_high_complexity_section(high_complexity_items)
    
    md_content += "## Guidelines\n\n"
    md_content += "- **Cyclomatic Complexity (CCN)**: Measure of code complexity based on decision points\n"
    md_content += "  - **Good**: CCN ≤ 10\n"
    md_content += "  - **Warning**: 10 < CCN ≤ 15\n"
    md_content += "  - **Critical**: CCN > 15\n\n"
    md_content += "- **Function Length (NLOC)**: Number of lines of code\n"
    md_content += "  - Target: Keep functions under 50 lines\n"
    md_content += "  - For this static template, code should be minimal\n\n"
    md_content += "- **Threshold**: Any function with CCN > 10 should be reviewed and simplified\n\n"
    md_content += "## More Information\n\n"
    md_content += "- Generated by [Lizard](http://www.lizard.ws/)\n"
    md_content += "- Reports location: `.complexity-reports/`\n"
    md_content += "  - `complexity-report.md` (this file)\n"
    md_content += "  - `complexity-report.csv` (machine-readable)\n"
    
    return md_content


def write_report(report_path, content):
    """Write markdown report to file."""
    try:
        with open(report_path, "w") as f:
            f.write(content)
    except Exception as e:
        raise RuntimeError(f"Failed to write markdown report: {e}") from e


def main():
    """Generate markdown report from complexity analysis files."""
    os.makedirs(".complexity-reports", exist_ok=True)
    
    csv_path = ".complexity-reports/complexity-report.csv"
    raw_path = ".complexity-reports/complexity-report-raw.txt"
    report_path = ".complexity-reports/complexity-report.md"
    
    # Read input files
    high_complexity_items = read_csv_report(csv_path)
    summary_lines = read_raw_report(raw_path)
    
    # Generate report
    report_content = build_markdown_report(summary_lines, high_complexity_items)
    write_report(report_path, report_content)
    
    print("✅ Markdown report generated successfully")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"❌ Error generating markdown report: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)

